"""empty message

Revision ID: 1dc37afd6bb3
Revises: 4476b09123b0
Create Date: 2015-08-04 12:19:43.647806

"""

# revision identifiers, used by Alembic.
revision = '1dc37afd6bb3'
down_revision = '4476b09123b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('migrationtest', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'migrationtest')
    ### end Alembic commands ###
