"""empty message

Revision ID: 2b08ecc0478d
Revises: None
Create Date: 2015-08-05 18:20:51.250028

"""

# revision identifiers, used by Alembic.
revision = '2b08ecc0478d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False)
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False)
    op.drop_column('user', 'migrationtest')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('migrationtest', sa.VARCHAR(length=80), nullable=True))
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=True)
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=True)
    ### end Alembic commands ###
