"""empty message

Revision ID: 4476b09123b0
Revises: None
Create Date: 2015-08-04 12:16:21.205329

"""

# revision identifiers, used by Alembic.
revision = '4476b09123b0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
